      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install vcpkg
        run: |
          git clone --depth=1 https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      - name: Get dependencies, configure and build
        run: |
          cmake . -DCMAKE_TOOLCHAIN_FILE="vcpkg\scripts\buildsystems\vcpkg.cmake" -B build
          cmake --build build