on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ~/vcpkg
          key: ${{ hashFiles('vcpkg.json') }}
      
      - name: install vcpkg
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      - name: Get dependencies, configure and build
        run: |
          cmake . -DCMAKE_TOOLCHAIN_FILE="vcpkg\scripts\buildsystems\vcpkg.cmake" -B build
          cmake --build build --config Release
          Compress-Archive -CompressionLevel Optimal -Path .\build\x64 -DestinationPath build.zip

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release.zip'
          path: 'build\x64'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}