on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install vcpkg
        run: |
          git clone --depth=1 https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      - name: Get dependencies, configure and build
        run: |
          cmake . -DCMAKE_TOOLCHAIN_FILE="vcpkg\scripts\buildsystems\vcpkg.cmake" -B build
          cmake --build build --config Release
          Compress-Archive -CompressionLevel Optimal Compress-Archive -Path .\build\x64 -DestinationPath build.zip

      - name: Create Release
        uses: aaiezza/create-release@master
        id: create_release
        with:
          release_branch: feature/windows-hacks-1
          tag: ${{ env.GITHUB_RUN_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build.zip
          asset_name: build.zip